# Generated by Django 4.0 on 2022-07-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_profile_updated'),
        ('jobapp', '0018_news_delete_jobalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=10)),
                ('icon', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('meta_title', models.TextField(default='')),
                ('meta_description', models.TextField(default='')),
                ('page_content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('unsubscribe_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_unsubscribe', models.BooleanField(default=False)),
                ('subscribe_code', models.CharField(blank=True, max_length=100, null=True)),
                ('unsubscribe_reason', models.TextField(default='')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.skill')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=2000, unique=True)),
                ('unsubscribe_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_unsubscribe', models.BooleanField(default=False)),
                ('subscribe_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('unsubscribe_reason', models.TextField(default='')),
                ('skill', models.ManyToManyField(to='jobapp.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='DailySearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_job_posts', models.IntegerField(default='0')),
                ('created_on', models.DateField()),
                ('no_of_searches', models.IntegerField(default='0')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.skill')),
            ],
        ),
    ]
