# Generated by Django 4.0 on 2022-08-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_skill_subscriber_jobalert_dailysearchlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
