# Generated by Django 4.0 on 2022-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_alter_job_job_type_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ranking',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
