# Generated by Django 4.0 on 2022-10-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_profile_updated'),
        ('jobapp', '0022_applicant_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapp.job')),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messaged_from', to='account.user')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_to', to='account.user')),
            ],
        ),
    ]
