# Generated by Django 4.0 on 2022-07-24 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_activation_code_user_current_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
